#!/usr/bin/env python3
"""Generate the C++ field table used by the iOS parameter panel.

Android builds its parameter UI with Java reflection over the SWIG classes
(see android/aoceswigtest/.../ParametAdapter.java). C++ has no reflection, so
this script parses the plain parameter structs in the aoce headers and emits a
table of (struct type, field name, field type, offset). offsetof() makes the
compiler verify every entry against the real struct layout.

Usage: python3 ios/tools/gen_param_fields.py   (run from anywhere)
"""
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
HEADERS = [
    "code/aoce/AoceMath.h",
    "code/aoce/Aoce.h",
    "code/aoce/AoceLayer.h",
    "code/aoce_vulkan_extra/AoceVkExtra.h",
]
OUTPUT = os.path.join(ROOT, "ios", "aoceswigtest", "ParamFields.gen.cpp")

STRUCT_RE = re.compile(r"^struct\s+(\w+)\s*\{")
FIELD_RE = re.compile(r"^\s+([A-Za-z_][\w:]*)\s+([A-Za-z_]\w*)\s*(=[^;]*)?;")


def parse_structs(path):
    structs = []
    current = None
    depth = 0
    with open(path, encoding="utf-8") as f:
        for line in f:
            code = line.split("//")[0].rstrip()
            if current is None:
                m = STRUCT_RE.match(code)
                if m:
                    current = (m.group(1), [])
                    depth = code.count("{") - code.count("}")
                continue
            if depth == 1 and "(" not in code:
                m = FIELD_RE.match(code)
                if m and m.group(1) not in ("return", "typedef", "using"):
                    current[1].append((m.group(1), m.group(2)))
            depth += code.count("{") - code.count("}")
            if depth <= 0:
                structs.append(current)
                current = None
    return structs


def is_param_struct(name):
    # metadata只会引用参数结构体以及其中的向量/矩阵
    return name.endswith("Paramet") or name in ("vec2", "vec3", "vec4", "Mat3x3", "Mat4x4")


def main():
    structs = []
    for header in HEADERS:
        structs.extend(s for s in parse_structs(os.path.join(ROOT, header)) if is_param_struct(s[0]))
    lines = [
        "// Generated by ios/tools/gen_param_fields.py - do not edit.",
        "#include <cstddef>",
        "",
        '#include "ParamFields.hpp"',
        '#include "aoce/AoceCore.h"',
        '#include "aoce_vulkan_extra/AoceVkExtra.h"',
        "",
        "using namespace aoce;",
        "",
        "// offsetof on types with default member initializers",
        "#pragma clang diagnostic ignored \"-Winvalid-offsetof\"",
        "",
        "const ParamField kParamFields[] = {",
    ]
    count = 0
    for name, fields in structs:
        for ftype, fname in fields:
            lines.append(
                f'    {{&typeid({name}), "{fname}", &typeid({ftype}), '
                f"offsetof({name}, {fname})}},"
            )
            count += 1
    lines.append("};")
    lines.append("")
    lines.append(
        "const size_t kParamFieldCount = sizeof(kParamFields) / sizeof(kParamFields[0]);"
    )
    lines.append("")
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"{len(structs)} structs, {count} fields -> {os.path.relpath(OUTPUT, ROOT)}")


if __name__ == "__main__":
    main()
